$ANSIBLE_VAULT;1.1;AES256
33656362383562316132356265313437383162326237663334636434666563356665393634396466
6466323138306463653838656332636332666464373065370a616161656235353964636631356136
66656438336162623736623364626332393530303862633233326632363265356236633935646531
6632663033333531370a646538333237323261376138373331663635623533393237373865636337
32303962626563346132383132386561613166363836633331353633373638663631623964633034
64373266326662313239663662356466636130356436376531376632616230626532353331396331
36376264363333643730646439643564346630326661353633336666303961313332643665666461
32336435363964346636363663636138333565366166646666383938336433613034613363343436
33366165306430626338663565306563336534616362663539653462643765623861626237626438
38613666393761613838363735626566643139313834343836353635336131376664656533346266
32356130666163643865363565323730373438313632656432626437656232383236333535626362
33663865633033633636633334633764386534626261343364656235306337376364303437636664
39373363393232336237343530333631303836316435343165663835366664346331393466366565
66616534343138363363373330336566376132643837323066663230303561643236376331663238
35346239613863396161666332626161653861303731666265613032346261366264653762373233
66303334623565356266653034313734633232616437363966396664633134336130666366633562
39333462366561643630653336343831343732343862663266313464303535636634313764336633
61666330623834386330353163353736616139653765323232626439636633363065613732313031
323437653238356530313064636537343633
