openapi: 3.0.3
info:
  title: Motorcade People & Careers API
  version: 0.0.0
paths:
  /api/v1/applicants:
    post:
      summary: Create applicant
      responses:
        '201':
          description: Created
