collections:
  - name: community.general
    version: "12.2.0"
  - name: ansible.posix
    version: "2.1.0"
  - name: community.crypto
    version: "3.1.0"
  - name: containers.podman
    version: "1.18.1"
  - name: amazon.aws
  - name: community.aws
  - name: ansible.utils
  - name: community.hashi_vault
  - name: nginxinc.nginx
  - name: community.postgresql
  - name: kubernetes.core
  - name: community.docker
